### ISSUE TITLE
The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft'

### ISSUE THREAD

**Issue by aaani** [Azure-Samples/media-services-dotnet-deliver-playready-widevine-licenses#3]
I am getting these errors when I build on Mac 10.13.4:

```
/media-services-dotnet-deliver-playready-widevine-licenses/DeliverDRMLicenses/DeliverDRMLicenses/Program.cs(17,17): Error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) (CS0234) (DeliverDRMLicenses)

/media-services-dotnet-deliver-playready-widevine-licenses/DeliverDRMLicenses/DeliverDRMLicenses/Program.cs(17,17): Error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) (CS0234) (DeliverDRMLicenses)

/media-services-dotnet-deliver-playready-widevine-licenses/DeliverDRMLicenses/DeliverDRMLicenses/Program.cs(17,17): Error CS0234: The type or namespace name 'WindowsAzure' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) (CS0234) (DeliverDRMLicenses)

/media-services-dotnet-deliver-playready-widevine-licenses/DeliverDRMLicenses/DeliverDRMLicenses/Program.cs(7,7): Error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (DeliverDRMLicenses)

/media-services-dotnet-deliver-playready-widevine-licenses/DeliverDRMLicenses/DeliverDRMLicenses/Program.cs(55,55): Error CS0246: The type or namespace name 'IContentKey' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (DeliverDRMLicenses)

/media-services-dotnet-deliver-playready-widevine-licenses/DeliverDRMLicenses/DeliverDRMLicenses/Program.cs(68,68): Error CS0246: The type or namespace name 'IContentKey' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (DeliverDRMLicenses)

/media-services-dotnet-deliver-playready-widevine-licenses/DeliverDRMLicenses/DeliverDRMLicenses/Program.cs(23,23): Error CS0246: The type or namespace name 'IContentKey' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (DeliverDRMLicenses)

/media-services-dotnet-deliver-playready-widevine-licenses/DeliverDRMLicenses/DeliverDRMLicenses/Program.cs(24,24): Error CS0246: The type or namespace name 'CloudMediaContext' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (DeliverDRMLicenses)
```

Please advise

**Comment by Juliako** [comment]
Hi @aani, you cannot build Media Services v2 on MAC, it does not support .NET Core.

**Comment by Juliako** [comment]
#please-close

**Comment by johndeu** [comment]
Re: build on Mac 10.13.4
This is not a .NET core project, since this is the v2 SDK for Media Services and not v3, this sample does not compile for .NET Core and would likely fail on a Mac.

**Comment by aaani** [comment]
Thanks @Juliako and @johndeu !

**Comment by aaani** [comment]
@Juliako @johndeu Is there a node.js SDK or Sample for deploying a playready licensing server on Azure? I am following this article - https://azure.microsoft.com/en-us/resources/samples/media-services-dotnet-deliver-playready-widevine-licenses/

**Comment by gvsro** [comment]
@aaani As far as I know (and I searched for a long time) the node sdk does not support it. The nodejs media services sdk is only for managing resources. Check the rest api, make requests from node and parse them.

**Comment by johndeu** [comment]
There is a new v3 NodeJS SDK available. It does a lot more than just management in our v3 API.

Unfortunately for you though,  we have not yet prioritized creating any Playready documentation or samples on the v3 APIs (especially node) yet. We are focusing only on the core scenarios for Encoding, Analytics and Streaming right now to get the v3 docs all filled in for those.  We will probbaly tackle DRM after we GA the v3 APIs. I can connect you with folks on the team playing with v3 and DRM scenarios if needed.

**Comment by johndeu** [comment]
can you list off the scenarios and samples that you would like to see?

**Comment by gvsro** [comment]
A complete nodejs example just like the one written in c# [here](https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-deliver-keys-and-licenses)

**Comment by aaani** [comment]
@johndeu An example showing Playready DRM license delivery only (which leverages Content hosting & origin and Content encryption from Third-party/on-premise servers) using node.js SDK would be great. The C# example @gvsro mentioned does the same. 

If you can connect me with the folks at Microsoft that are playing with v3 and DRM scenarios that would be even better.

Apologies for derailing the discussion from the originally reported .NET build error.

**Comment by willzhan** [comment]
@aaani I recently wrote some DRM code using v3 .NET SDK. Considering both Node.JS and .NET SDK are generated from the same REST API, some level of similarity exists. I would be happy to share my code with you if that helps. Please ping me at willzhan@microsoft.com

**Comment by aaani** [comment]
@johndeu Does the V3 of the SDK even support the workflow mentioned in https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-deliver-keys-and-licenses? The code @willzhan shared uploads an asset, apply content key policies to that asset and then get paths from from it. In my use case (also in the references article) the assets exist on the in premise server and Azure media services are used only for key/license delivery.
